---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gopublicom/api.gopubli.com.br

    # Copiar arquivos
    - /bin/cp -R * $DEPLOYPATH

    # Garantir permissões
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache

    # Limpar cache antigo
    - /usr/bin/find $DEPLOYPATH/bootstrap/cache -type f -delete

    # Rodar Laravel com PHP do cPanel
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan key:generate || true
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan migrate --force || true
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan config:clear || true
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan route:clear || true
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan view:clear || true
