---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gopublicom/api.gopubli.com.br

    # Copiar arquivos SEM .git
    - /bin/rsync -av --delete --exclude=".git" ./ $DEPLOYPATH

    # Permissões corretas
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache

    # Limpar cache antigo (seguro)
    - /usr/bin/find $DEPLOYPATH/bootstrap/cache -type f -delete

    # Limpar caches Laravel (sem quebrar produção)
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan config:clear || true
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan route:clear || true
    - /opt/cpanel/ea-php83/root/bin/php $DEPLOYPATH/artisan view:clear || true
